### PR TITLE
Add SpecialRootFeature button

### PR DESCRIPTION
**Pull request by phelgo**
This PR displays an extra button on the root node that can be used to select a custom feature.

### CODE REVIEW

**Comment by cabeca** [comment]
Looks good!

**Comment by cabeca** [comment]
Change the pod version and this is good to merge.

**Comment by phelgo** [comment]
Fantastic, going to do it!

**Comment by phelgo** [comment]
Done!

**Comment by cabeca** [comment]
You should update the pod version to "0.1.11". In master it is already at "0.1.10"

**Comment by phelgo** [comment]
Thanks, didn't notice that, just a second

**Comment by phelgo** [comment]
Done!

**Pull request merged**
